name: tp0
networks:
  testing_net:
    ipam:
      config:
      - subnet: 172.25.125.0/24
      driver: default
services:
  client1:
    container_name: client1
    depends_on:
    - server
    entrypoint: /client
    environment:
    - CLI_ID=1
    - CLI_LOG_LEVEL=DEBUG
    - NOMBRE=Franco
    - APELLIDO=Rodriguez
    - DOCUMENTO=76547719
    - NACIMIENTO=1969-12-30
    - NUMERO=8502
    image: client:latest
    networks:
    - testing_net
    volumes:
    - ./client/config.yaml:/config.yaml
  client2:
    container_name: client2
    depends_on:
    - server
    entrypoint: /client
    environment:
    - CLI_ID=2
    - CLI_LOG_LEVEL=DEBUG
    - NOMBRE=Roberto
    - APELLIDO=Perez
    - DOCUMENTO=53239295
    - NACIMIENTO=1979-11-18
    - NUMERO=6139
    image: client:latest
    networks:
    - testing_net
    volumes:
    - ./client/config.yaml:/config.yaml
  client3:
    container_name: client3
    depends_on:
    - server
    entrypoint: /client
    environment:
    - CLI_ID=3
    - CLI_LOG_LEVEL=DEBUG
    - NOMBRE=Roberto
    - APELLIDO=Alvarez
    - DOCUMENTO=94910283
    - NACIMIENTO=1996-09-09
    - NUMERO=2416
    image: client:latest
    networks:
    - testing_net
    volumes:
    - ./client/config.yaml:/config.yaml
  server:
    container_name: server
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    image: server:latest
    networks:
    - testing_net
    volumes:
    - ./server/config.ini:/config.ini
